FROM %%PHP_VERSION%%

RUN set -xe && \
        apk add --no-cache tini

RUN set -xe && \
        curl -LOs https://phar.phpunit.de/phpunit.phar && \
        chmod +x phpunit.phar && \
        mv phpunit.phar /usr/local/bin/phpunit

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
