name: Testing

on:
  push:
    branches:
      - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: PHPUnit test
        uses: mileschou/docker-phpunit@master
        with:
          args: --help
